[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  REPORTS_API_TOKEN = ""
  VITE_REPORTS_API_TOKEN = ""
  REPORTS_ALLOWED_ORIGIN = "https://www.gepservices.es"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
