export const players = [
  {
    id: 'p1',
    name: 'Carlos Ruiz',
    rating: 8.6,
    form: 0.78,
    consistency: 0.84,
    aggressiveness: 0.63,
    defense: 0.79,
    netPlay: 0.74,
    preferredSide: 'revés',
    winRate: 0.68,
    matches: 48,
    clutch: 0.66,
    streak: 4,
    recent: ['W', 'W', 'W', 'L', 'W'],
  },
  {
    id: 'p2',
    name: 'Diego López',
    rating: 8.1,
    form: 0.74,
    consistency: 0.81,
    aggressiveness: 0.58,
    defense: 0.76,
    netPlay: 0.72,
    preferredSide: 'drive',
    winRate: 0.65,
    matches: 45,
    clutch: 0.61,
    streak: 3,
    recent: ['W', 'W', 'L', 'W', 'W'],
  },
  {
    id: 'p3',
    name: 'Álvaro Medina',
    rating: 7.9,
    form: 0.7,
    consistency: 0.78,
    aggressiveness: 0.6,
    defense: 0.73,
    netPlay: 0.69,
    preferredSide: 'revés',
    winRate: 0.61,
    matches: 38,
    clutch: 0.58,
    streak: 1,
    recent: ['W', 'L', 'W', 'W', 'L'],
  },
  {
    id: 'p4',
    name: 'Marcos Vidal',
    rating: 8.9,
    form: 0.82,
    consistency: 0.86,
    aggressiveness: 0.71,
    defense: 0.77,
    netPlay: 0.8,
    preferredSide: 'revés',
    winRate: 0.72,
    matches: 52,
    clutch: 0.69,
    streak: 5,
    recent: ['W', 'W', 'W', 'W', 'W'],
  },
  {
    id: 'p5',
    name: 'Javier Ortiz',
    rating: 7.5,
    form: 0.62,
    consistency: 0.71,
    aggressiveness: 0.49,
    defense: 0.7,
    netPlay: 0.65,
    preferredSide: 'drive',
    winRate: 0.54,
    matches: 34,
    clutch: 0.52,
    streak: -1,
    recent: ['L', 'W', 'W', 'L', 'W'],
  },
  {
    id: 'p6',
    name: 'Sergio Navas',
    rating: 7.7,
    form: 0.67,
    consistency: 0.75,
    aggressiveness: 0.55,
    defense: 0.76,
    netPlay: 0.66,
    preferredSide: 'drive',
    winRate: 0.58,
    matches: 36,
    clutch: 0.57,
    streak: 2,
    recent: ['W', 'W', 'L', 'W', 'L'],
  },
  {
    id: 'p7',
    name: 'Nico Fernández',
    rating: 8.2,
    form: 0.76,
    consistency: 0.83,
    aggressiveness: 0.62,
    defense: 0.75,
    netPlay: 0.78,
    preferredSide: 'drive',
    winRate: 0.69,
    matches: 41,
    clutch: 0.64,
    streak: 3,
    recent: ['W', 'W', 'W', 'L', 'W'],
  },
  {
    id: 'p8',
    name: 'Pablo Ramos',
    rating: 7.3,
    form: 0.6,
    consistency: 0.68,
    aggressiveness: 0.47,
    defense: 0.72,
    netPlay: 0.63,
    preferredSide: 'revés',
    winRate: 0.52,
    matches: 31,
    clutch: 0.5,
    streak: -2,
    recent: ['L', 'L', 'W', 'L', 'W'],
  },
  {
    id: 'p9',
    name: 'Iván Calderón',
    rating: 7.8,
    form: 0.71,
    consistency: 0.77,
    aggressiveness: 0.57,
    defense: 0.74,
    netPlay: 0.68,
    preferredSide: 'revés',
    winRate: 0.6,
    matches: 39,
    clutch: 0.59,
    streak: 2,
    recent: ['W', 'L', 'W', 'W', 'W'],
  },
  {
    id: 'p10',
    name: 'Luis Castillo',
    rating: 7.1,
    form: 0.58,
    consistency: 0.65,
    aggressiveness: 0.44,
    defense: 0.69,
    netPlay: 0.6,
    preferredSide: 'drive',
    winRate: 0.49,
    matches: 28,
    clutch: 0.48,
    streak: -1,
    recent: ['W', 'L', 'L', 'W', 'L'],
  },
]

export const pairStats = [
  {
    players: ['p1', 'p2'],
    matches: 18,
    wins: 13,
    pointsDiff: 28,
    tieBreakWinRate: 0.62,
    chemistry: 0.86,
    style: 'Control y contraataque',
    trend: 'up',
  },
  {
    players: ['p4', 'p7'],
    matches: 20,
    wins: 15,
    pointsDiff: 32,
    tieBreakWinRate: 0.66,
    chemistry: 0.88,
    style: 'Ofensiva inteligente',
    trend: 'up',
  },
  {
    players: ['p1', 'p4'],
    matches: 10,
    wins: 7,
    pointsDiff: 14,
    tieBreakWinRate: 0.6,
    chemistry: 0.82,
    style: 'Potencia desde el revés',
    trend: 'steady',
  },
  {
    players: ['p3', 'p5'],
    matches: 12,
    wins: 7,
    pointsDiff: 6,
    tieBreakWinRate: 0.55,
    chemistry: 0.73,
    style: 'Control táctico',
    trend: 'steady',
  },
  {
    players: ['p6', 'p8'],
    matches: 11,
    wins: 6,
    pointsDiff: 2,
    tieBreakWinRate: 0.5,
    chemistry: 0.68,
    style: 'Defensa y globo',
    trend: 'down',
  },
  {
    players: ['p2', 'p9'],
    matches: 14,
    wins: 9,
    pointsDiff: 10,
    tieBreakWinRate: 0.58,
    chemistry: 0.78,
    style: 'Juego equilibrado',
    trend: 'up',
  },
  {
    players: ['p5', 'p10'],
    matches: 9,
    wins: 4,
    pointsDiff: -4,
    tieBreakWinRate: 0.47,
    chemistry: 0.62,
    style: 'Control y paciencia',
    trend: 'steady',
  },
  {
    players: ['p3', 'p6'],
    matches: 13,
    wins: 8,
    pointsDiff: 5,
    tieBreakWinRate: 0.52,
    chemistry: 0.75,
    style: 'Construcción paciente',
    trend: 'steady',
  },
  {
    players: ['p7', 'p9'],
    matches: 16,
    wins: 11,
    pointsDiff: 18,
    tieBreakWinRate: 0.6,
    chemistry: 0.81,
    style: 'Ofensiva ordenada',
    trend: 'up',
  },
  {
    players: ['p2', 'p7'],
    matches: 8,
    wins: 5,
    pointsDiff: 7,
    tieBreakWinRate: 0.57,
    chemistry: 0.77,
    style: 'Ataque desde la red',
    trend: 'steady',
  },
  {
    players: ['p4', 'p9'],
    matches: 9,
    wins: 6,
    pointsDiff: 12,
    tieBreakWinRate: 0.59,
    chemistry: 0.8,
    style: 'Revés dominante',
    trend: 'up',
  },
  {
    players: ['p6', 'p10'],
    matches: 7,
    wins: 3,
    pointsDiff: -6,
    tieBreakWinRate: 0.45,
    chemistry: 0.65,
    style: 'Defensa clásica',
    trend: 'down',
  },
]
